config/routes.rb
Rails.application.routes.draw do
  get '/contact' => 'pages#contact', as: :contact_page
  get '/about' => 'pages#about', as: :about_page
  root to: 'pages#home'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_filter :subdomain_view_path

  def home

  end

  private

  def subdomain_view_path
    prepend_view_path "app/views/#{request.subdomain}" if request.subdomain.present?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/catelax/pages/about.html.slim
h1 About Catelax
.post.panel.panel-default
  .panel-body
  p Engineered on the highest point of a valley, the crossroad of Pernrith is home to giants lead by Ruler Gedman.

  p This crossroad wasn't built by a valley by accident, as it has healing properties, which is of great importance to the people of Pernrith and its success.

  p The crossroad itself looks crude. With its rusted rooftops, worn limestone walls and murky woods, Pernrith has a unearthly atmosphere.

  p The main attraction is the stables, which was built 28 years ago and designed by humans.

  p Pernrith has a feeble economy, which is mainly supported by woodcrafting, animal training and carpenting. But their biggest strengths are rare animal training and weaponsmithing.

  p However, Pernrith lacks people skilled in engineering.

  p Despite its strengths and weaknesses, Pernrith is most likely headed towards a horrible future under the leadership of Ruler Gedman. But this remains to be seen.

app/views/catelax/pages/contact.html.slim
h1 Contact Catelax
.post.panel.panel-default
  .panel-body
    p Designed on the Northern side of a covert, the village of Haran is home to pirates lead by Captain Massey.

    p This village wasn't built by a covert by accident, as it has spiritual significance, which is of great importance to the people of Haran and its success.

    p The village itself looks rough. With its gloomy wooden rooftops, faded marble walls and musky swamps, Haran has a bleak atmosphere.

    p The main attraction is the ancient forge, which was built 28 years ago and designed by barbarians.

    p Haran has a prosperous economy, which is mainly supported by mining, woodcrafting and alchemy. But their biggest strengths are ancient wine brewing techniques and rare animal breeding.

    p However, Haran lacks people skilled in leatherworking.

    p Despite its strengths and weaknesses, Haran is most likely headed towards a cheerful future under the leadership of Captain Massey. But this remains to be seen.

app/views/catelax/pages/home.html.slim
h1 Welcome to Catelax
.post.panel.panel-default
  .panel-body
    p This subdomain uses default layout, but views are different

app/views/chimora/layouts/_navigation.html.slim
/ navigation styled for Bootstrap 3.0
nav.navbar.navbar-fixed-top
  .container
    .navbar-header
      button.navbar-toggle[type="button" data-toggle="collapse" data-target=".navbar-collapse"]
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      ul.nav.navbar-nav
        == render 'layouts/navigation_links'

app/views/chimora/layouts/application.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : 'Tarra'
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Chimora'}"
    == stylesheet_link_tag "application", media: 'all'
    == stylesheet_link_tag "chimora", media: 'all'
    == stylesheet_link_tag("#{request.subdomain}", media: 'all') if request.subdomain.present?
    == javascript_include_tag 'application', 'data-turbolinks-track' => true
    == csrf_meta_tags
  body
    header
      == render 'layouts/navigation'
    main[role="main"]
      .container
        == render 'layouts/messages'
        == yield

app/views/chimora/pages/home.html.slim
h1 Welcome to Chimora
.post.panel.panel-default
  .panel-body
    p This subdomain uses own layout, pages except home page are default

app/views/layouts/_messages.html.slim
/ Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class="alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"
      button.close[type="button" data-dismiss="alert" aria-hidden="true"] ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.slim
/ navigation styled for Bootstrap 3.0
nav.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      button.navbar-toggle[type="button" data-toggle="collapse" data-target=".navbar-collapse"]
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      ul.nav.navbar-nav
        == render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.slim
li = link_to 'About', about_page_path
li = link_to 'Contact', contact_page_path

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : 'Tarra'
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Tarra'}"
    == stylesheet_link_tag "application", media: 'all'
    == stylesheet_link_tag("#{request.subdomain}", media: 'all') if request.subdomain.present?
    == javascript_include_tag 'application', 'data-turbolinks-track' => true
    == csrf_meta_tags
  body
    header
      == render 'layouts/navigation'
    main[role="main"]
      == render 'layouts/messages'
      == yield

app/views/pages/about.html.slim
h1 Default About
.post.panel.panel-default
  .panel-body
    p The planet Endor, named so for the planet's properties, is an ice planet in a vast solar system with twenty-five other planets.

    p Endor is about 1.0 times bigger than Earth and its gravity is about 1.08 times that of Earth.

    p A single day lasts 20.56 hours and a year lasts 227 days. The planet is made up of 8 continents, which make up 45% of the planet's landmass.

    p 5 moons orbit the planet and Endor itself orbits an orange sun in a wide, elliptic orbit.

    p With conditions as extreme as these, the chances of sustaining life on this planet are virtually none-existent. Even if the planet has calmed down after millions of years, it would probably still take terra forming to introduce any form of life.

app/views/pages/contact.html.slim
h1 Default Contacts
.post.panel.panel-default
  .panel-body
    p The planet Qo'noS, which is a name which is still disputed, is a desert planet in a huge solar system filled with twenty-two other planets.

    p Qo'noS is about 24.5 times bigger than Earth and its gravity is about 6.49 times that of Earth.

    p A single day lasts 26.82 hours and a year lasts 374 days. The planet is made up of 0 continents, which make up 0% of the planet's landmass.

    p 5 moons orbit the planet and Qo'noS itself orbits a blue sun in an almost perfectly circular orbit.

    p The plant-like organisms on this planet are exclusively different types of flowers. They come in all shapes and sizes, some are small and single stemmed, like you'd expect to find on Earth. But others are more like bushes, shrubs and even trees.

    p When nutrients are scarce, many organisms have methods of storing those nutrients for times of need. Some have become so specialized in this they can go for very long times without the need of additonal food, to then stock up when nutrients are available. However, some species on this planet didn't develop such methods. Instead, they simply take what they need, whenever they need it, from wherever they can. If nutrients aren't available in the ground, it will take them from others, including its own kind. This has occasionally lead to the survival of this species, but the downfall of another.

    p While the surface may have gorgeous forests of amazing organisms, the underwater world also has its fair share of forests. Mostly in the form of long, grass-like waterplants, but there are few dozens places on this planet where actual underwater forests grow. The species in these forests aren't actual trees, but they work in similar ways. Roots keep them in place, while a trunk helps carry the nutrients to every part of its body. At the top, branch-like tentacles grow to feed on micro-organisms near the surface. These tentacles often reach above the surface, giving the water a mysterious and eerie look.

    p The intelligent lifeforms on this planet are comparable to the humans of the bronze age, except that they are already more inclined to try to explain the mysteries of their world. Unfortunately they are quite violent, so they tend to live in smaller communities which they will protect at all costs. There are no signs of teamwork between the different communities, which would've been of benefit to them. This could lead to interesting developments in language and customs, but only time will tell how this will turn out.

app/views/pages/home.html.slim
h1 Welcome to Tarra project
.post.panel.panel-default
  .panel-body
    p This is an example project to show how Rails work with template inheritance

    p Check following subdomains
    ul
      li= link_to 'Catelax', root_url(subdomain: 'catelax')
      li= link_to 'Chimora', root_url(subdomain: 'chimora')